# Numpy 属性
* `ndim`: 维度
* `shape`: 行数和列数
* `size`: 元素个数

In [6]:
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
print("Array Dimensions:",array.ndim)
print("Array Shapes:",array.shape)
print("Array Size:",array.size)

Array Dimensions: 2
Array Shapes: (2, 3)
Array Size: 6


## Numpy 创建Array
* `array`: 创建数组
* `dtype`: 指定数据类型
* `zeros`: 创建元素全为0的数组
* `ones`: 创建元素全为1的数组
* `empty`：创建数据接近0的数组(float),数据为0的数组(int)
* `arrange`: 按指定范围创建数组
* `linspace`: 按数据区间段创建数组

In [8]:
array = np.array([[1,2,3],[2,3,4]]) 
array

array([[1, 2, 3],
       [2, 3, 4]])

In [12]:
array = np.array([1,2,3],dtype=np.float16)
print(array)
print(array.dtype)


[1. 2. 3.]
float16


In [18]:
array = np.zeros((3,4),dtype=np.int16)
print(array)
array.dtype

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


dtype('int16')

In [19]:
array = np.empty((3,4),dtype=np.int16)
array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [20]:
array = np.arange(10,20,2)
array

array([10, 12, 14, 16, 18])

In [21]:
array = np.arange(12).reshape((3,4))
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
array = np.linspace(1,10,20).reshape(4,5)
array

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684],
       [ 3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789],
       [ 5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895],
       [ 8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]])