# LearnNumpy

## 终端启动Jupyter notebook

In [ ]:
$ conda activate base
$ jupyter notebook

## Numpy 属性
* `ndim`: 维度
* `shape`: 行数和列数
* `size`: 元素个数

In [6]:
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
print("Array Dimensions:",array.ndim)
print("Array Shapes:",array.shape)
print("Array Size:",array.size)

Array Dimensions: 2
Array Shapes: (2, 3)
Array Size: 6


## Numpy 创建Array
* `array`: 创建数组
* `dtype`: 指定数据类型
* `zeros`: 创建元素全为0的数组
* `ones`: 创建元素全为1的数组
* `empty`：创建数据接近0的数组(float),数据为0的数组(int)
* `arrange`: 按指定范围创建数组
* `linspace`: 按数据区间段创建数组

In [8]:
array = np.array([[1,2,3],[2,3,4]]) 
array

array([[1, 2, 3],
       [2, 3, 4]])

In [12]:
array = np.array([1,2,3],dtype=np.float16)
print(array)
print(array.dtype)


[1. 2. 3.]
float16


In [18]:
array = np.zeros((3,4),dtype=np.int16)
print(array)
array.dtype

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


dtype('int16')

In [19]:
array = np.empty((3,4),dtype=np.int16)
array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [20]:
array = np.arange(10,20,2)
array

array([10, 12, 14, 16, 18])

In [21]:
array = np.arange(12).reshape((3,4))
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
array = np.linspace(1,10,20).reshape(4,5)
array

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684],
       [ 3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789],
       [ 5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895],
       [ 8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]])

## Numpy 基本运算

In [48]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array.max()) # 最大值

12


In [49]:
print(array.min()) # 最小值

1


In [50]:
print(array.mean()) # 平均数

6.5


In [51]:
print(np.cumsum(array)) # 每一个元素都是它前面所有元素的累加和
print(array.cumsum()) # 每一个元素都是它前面所有元素的累加和

[ 1  3  6 10 15 21 28 36 45 55 66 78]
[ 1  3  6 10 15 21 28 36 45 55 66 78]


In [52]:
print(np.median(array)) # 中位数

6.5


In [53]:
print(np.diff(array)) # 每一行中后一项与前一项之差

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [54]:
print(np.nonzero(array)) # 将非零元素的行列分开，分别重构成行和列的矩阵

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))


In [61]:
array = np.arange(14,2,-1)
print(array)
print(array.reshape(3,4))
print(array.reshape(3,4).T)
print(np.sort(array.reshape(3,4)))
print(array.clip(5,11))
print(np.clip(array,7,10))

[14 13 12 11 10  9  8  7  6  5  4  3]
[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
[11 11 11 11 10  9  8  7  6  5  5  5]
[10 10 10 10 10  9  8  7  7  7  7  7]


In [72]:
a = np.arange(0,4).reshape(2,2)
b = np.ones((2,2))
print("a+b =",a+b)
print("a*b =",a*b)
print("a**2 =",a**2)
print("np.dot(a,b)=",np.dot(a,b))

a+b = [[1. 2.]
 [3. 4.]]
a*b = [[0. 1.]
 [2. 3.]]
a**2 = [[0 1]
 [4 9]]
np.dot(a,b)= [[1. 1.]
 [5. 5.]]


In [73]:
a = np.random.random((2,4))
a

array([[0.71764637, 0.16508236, 0.41176364, 0.66205923],
       [0.11197349, 0.65117745, 0.37664658, 0.4372579 ]])

In [74]:
a.sum()

3.53360702053231

In [82]:
a.min()

0.11197349147663271

In [81]:
a.max()

0.7176463710535458

In [77]:
a.sum(axis=0)

array([0.82961986, 0.81625982, 0.78841021, 1.09931713])

In [78]:
a.sum(axis=1)

array([1.9565516 , 1.57705542])

## Numpy 索引

In [83]:
a = np.arange(3,15)
a

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [84]:
a[3]

6

In [86]:
A = a.reshape(3,4)
A

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [87]:
A[2]

array([11, 12, 13, 14])

In [89]:
A[1,2]

9

In [90]:
A[1][2]

9

In [91]:
A.T

array([[ 3,  7, 11],
       [ 4,  8, 12],
       [ 5,  9, 13],
       [ 6, 10, 14]])

In [92]:
A.flatten()

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [93]:
for item in A.flat:
    print(item)

3
4
5
6
7
8
9
10
11
12
13
14


## Numpy Array 合并

In [95]:
a = np.ones(3)
b = np.zeros(3) 
print("a=",a) 
print("b=",b)

a= [1. 1. 1.]
b= [0. 0. 0.]


In [99]:
np.vstack((a,b))

array([[1., 1., 1.],
       [0., 0., 0.]])

In [100]:
np.hstack((a,b))

array([1., 1., 1., 0., 0., 0.])

In [101]:
a.T

array([1., 1., 1.])

In [121]:
print(a)
print("a.shape=",a.shape)
print(a[np.newaxis,:])
print("a[np.newaxis,:]=",a[np.newaxis,:].shape)

[1. 1. 1.]
a.shape= (3,)
[[1. 1. 1.]]
a[np.newaxis,:]= (1, 3)


In [116]:
a[np.newaxis,np.newaxis].shape

(1, 1, 3)

In [106]:
a[np.newaxis,:].T

array([[1.],
       [1.],
       [1.]])

In [126]:
C = np.concatenate((a,b),axis=0)
C

array([1., 1., 1., 0., 0., 0.])

In [132]:
A = a[:,np.newaxis]
B = b[:,np.newaxis]
C = np.concatenate((A,B,A),axis=0)
C

array([[1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.]])

In [134]:
C = np.concatenate((A,B,A),axis=1)
C

array([[1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.]])

## Numpy array分割

In [135]:
a = np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [137]:
print(np.split(a,2,axis=1)) # Same with np.hsplit(a,2,axis=0)


[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [138]:
print(np.split(a,3,axis=0)) # Same with np.vsplit(a,3,axis=1)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [142]:
print(np.array_split(a,2,axis=0)) # 不等量分割

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


## Numpy array copy

In [145]:
a=np.arange(12).reshape((3,4))
a
b=a
b[1,1]=10
print("a=",a)
print("b=",b)

a= [[ 0  1  2  3]
 [ 4 10  6  7]
 [ 8  9 10 11]]
b= [[ 0  1  2  3]
 [ 4 10  6  7]
 [ 8  9 10 11]]


In [146]:
a=np.arange(12).reshape((3,4))
a
b=a.copy()
b[1,1]=10
print("a=",a)
print("b=",b)

a= [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b= [[ 0  1  2  3]
 [ 4 10  6  7]
 [ 8  9 10 11]]
